package com.example.poe.util

import android.util.Log

/**
 * Central Logger for the POE Budget Tracker.
 * This utility class provides a unified way to log messages across the application,
 * helping with debugging, tracking code flow, and handling errors.
 * It uses a global tag to make logs easily searchable in Logcat.
 */
object AppLogger {
    // The main tag used for all logs generated by this application
    private const val GLOBAL_TAG = "POE_BudgetTracker"

    /**
     * Logs a debug message. 
     * @param message The message to be logged.
     * @param subTag An optional specific tag to categorize the log (e.g., "UI", "DB").
     */
    fun d(message: String, subTag: String = "") {
        val logTag = if (subTag.isEmpty()) GLOBAL_TAG else "$GLOBAL_TAG-$subTag"
        Log.d(logTag, message)
    }

    /**
     * Logs an informational message.
     * @param message The message to be logged.
     * @param subTag An optional specific tag.
     */
    fun i(message: String, subTag: String = "") {
        val logTag = if (subTag.isEmpty()) GLOBAL_TAG else "$GLOBAL_TAG-$subTag"
        Log.i(logTag, message)
    }

    /**
     * Logs an error message along with an optional exception/throwable.
     * @param message The error description.
     * @param throwable An optional exception that caused the error.
     * @param subTag An optional specific tag.
     */
    fun e(message: String, throwable: Throwable? = null, subTag: String = "") {
        val logTag = if (subTag.isEmpty()) GLOBAL_TAG else "$GLOBAL_TAG-$subTag"
        Log.e(logTag, message, throwable)
    }
}
